[theme]
background = "default"
primary = "#FAF9F5"
secondary = "#A6A39A"
title = "#DA7756"
playing = "#DA7756"
playing_selected = "#262624"
playing_bg = "default"
highlight = "#262624"
highlight_bg = "#DA7756"
highlight_inactive_bg = "#403F3A"
error = "#FAF9F5"
error_bg = "#C1666B"
statusbar = "#DA7756"
statusbar_bg = "default"
statusbar_progress = "#DA7756"
statusbar_progress_bg = "#403F3A"
cmdline = "#FAF9F5"
cmdline_bg = "default"
search_match = "#F0A283"
